# Generated by Django 5.2.5 on 2025-08-06 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='branch',
            new_name='designation',
        ),
    ]
